// flow-typed signature: eb61b1cfa0911da46fd31824a4a4f208
// flow-typed version: <<STUB>>/esformatter-flow_v^1.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter-flow/esformatter-flow' {
  declare module.exports: any;
}

declare module 'esformatter-flow/test/compare.spec' {
  declare module.exports: any;
}

declare module 'esformatter-flow/test/compare/input' {
  declare module.exports: any;
}

declare module 'esformatter-flow/test/compare/output' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter-flow/esformatter-flow.js' {
  declare module.exports: $Exports<'esformatter-flow/esformatter-flow'>;
}
declare module 'esformatter-flow/test/compare.spec.js' {
  declare module.exports: $Exports<'esformatter-flow/test/compare.spec'>;
}
declare module 'esformatter-flow/test/compare/input.js' {
  declare module.exports: $Exports<'esformatter-flow/test/compare/input'>;
}
declare module 'esformatter-flow/test/compare/output.js' {
  declare module.exports: $Exports<'esformatter-flow/test/compare/output'>;
}
