// flow-typed signature: f28ec37259c28f10153c5e6495a2c3fb
// flow-typed version: <<STUB>>/esformatter-add-trailing-commas_v^1.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-add-trailing-commas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-add-trailing-commas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'esformatter-add-trailing-commas/index' {
  declare module.exports: $Exports<'esformatter-add-trailing-commas'>;
}
declare module 'esformatter-add-trailing-commas/index.js' {
  declare module.exports: $Exports<'esformatter-add-trailing-commas'>;
}
