// flow-typed signature: c41ac2b918797ea226134c80eed5a6d6
// flow-typed version: <<STUB>>/esformatter-limit-linebreaks_v0.0.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-limit-linebreaks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-limit-linebreaks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'esformatter-limit-linebreaks/index' {
  declare module.exports: $Exports<'esformatter-limit-linebreaks'>;
}
declare module 'esformatter-limit-linebreaks/index.js' {
  declare module.exports: $Exports<'esformatter-limit-linebreaks'>;
}
