// flow-typed signature: b4ce515e42ee6dee82bdd270ea5912bb
// flow-typed version: <<STUB>>/esformatter-align_v^0.2.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-align'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-align' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'esformatter-align/index' {
  declare module.exports: $Exports<'esformatter-align'>;
}
declare module 'esformatter-align/index.js' {
  declare module.exports: $Exports<'esformatter-align'>;
}
