// flow-typed signature: b5b3cb50458843ecc3eefd4b7d5ea8b1
// flow-typed version: <<STUB>>/koa-pino-logger_v^2.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-pino-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-pino-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-pino-logger/benchmarks/bunyan-server' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/benchmarks/koa-logger-server' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/benchmarks/koa-server' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/benchmarks/morgan-server' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/benchmarks/pino-error-server' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/benchmarks/pino-extreme-server' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/benchmarks/pino-server' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/benchmarks/raw-just-pino-server' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/error-example' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/example' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/logger' {
  declare module.exports: any;
}

declare module 'koa-pino-logger/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-pino-logger/benchmarks/bunyan-server.js' {
  declare module.exports: $Exports<'koa-pino-logger/benchmarks/bunyan-server'>;
}
declare module 'koa-pino-logger/benchmarks/koa-logger-server.js' {
  declare module.exports: $Exports<'koa-pino-logger/benchmarks/koa-logger-server'>;
}
declare module 'koa-pino-logger/benchmarks/koa-server.js' {
  declare module.exports: $Exports<'koa-pino-logger/benchmarks/koa-server'>;
}
declare module 'koa-pino-logger/benchmarks/morgan-server.js' {
  declare module.exports: $Exports<'koa-pino-logger/benchmarks/morgan-server'>;
}
declare module 'koa-pino-logger/benchmarks/pino-error-server.js' {
  declare module.exports: $Exports<'koa-pino-logger/benchmarks/pino-error-server'>;
}
declare module 'koa-pino-logger/benchmarks/pino-extreme-server.js' {
  declare module.exports: $Exports<'koa-pino-logger/benchmarks/pino-extreme-server'>;
}
declare module 'koa-pino-logger/benchmarks/pino-server.js' {
  declare module.exports: $Exports<'koa-pino-logger/benchmarks/pino-server'>;
}
declare module 'koa-pino-logger/benchmarks/raw-just-pino-server.js' {
  declare module.exports: $Exports<'koa-pino-logger/benchmarks/raw-just-pino-server'>;
}
declare module 'koa-pino-logger/error-example.js' {
  declare module.exports: $Exports<'koa-pino-logger/error-example'>;
}
declare module 'koa-pino-logger/example.js' {
  declare module.exports: $Exports<'koa-pino-logger/example'>;
}
declare module 'koa-pino-logger/logger.js' {
  declare module.exports: $Exports<'koa-pino-logger/logger'>;
}
declare module 'koa-pino-logger/test.js' {
  declare module.exports: $Exports<'koa-pino-logger/test'>;
}
