// flow-typed signature: bb00172202d042ab5ea789a63724ca85
// flow-typed version: <<STUB>>/koa-logger_v^1.3.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-logger/index' {
  declare module.exports: $Exports<'koa-logger'>;
}
declare module 'koa-logger/index.js' {
  declare module.exports: $Exports<'koa-logger'>;
}
